Repository LP23-1A/E-Commerce-Team-1, pull requests merged in 2024-03, with the labels that each got.

#13 test2
  backend/src/controller/user.ts
Labels: Feature

#15 sidebar done
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Icon/IncomeIcon.tsx
  frontend/src/Components/Icon/MainIcon.tsx
  frontend/src/Components/Icon/OrderIcon.tsx
  frontend/src/Components/Icon/ProductIcon.tsx
  frontend/src/Components/Icon/SettingsIcon.tsx
  frontend/src/Components/Navbar.tsx
  frontend/src/Components/Sidebar.tsx
  frontend/src/app/page.tsx
Labels: Feature

#20 Made Navbar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Icon/Bell.tsx
  frontend/src/Components/Icon/Logo.tsx
  frontend/src/Components/Icon/User.tsx
  frontend/src/Components/Navbar.tsx
Labels: Feature

#21 backend init
  backend/index.ts
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/utils/Database.ts
  backend/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/SVG/Apple.tsx
  frontend/src/Components/SVG/Google.tsx
  frontend/src/Components/SVG/Microsoft.tsx
  frontend/src/Components/SVG/PineCone.tsx
  frontend/src/Components/Sidebar.tsx
  frontend/src/app/InfoAboutStore/page.tsx
  frontend/src/app/SignUp/page.tsx
  frontend/src/app/globals.css
Labels: Feature

#26 2 feature sign up
  backend/package-lock.json
  backend/package.json
  backend/src/controller/user.ts
  backend/src/index.ts
  backend/src/model/user.ts
  backend/src/router/user.ts
  backend/src/utils/Database.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Alre-SignedUp.tsx
  frontend/src/Components/AuthProvider.tsx
  frontend/src/Components/ButtonApple.tsx
  frontend/src/Components/ButtonGoogle.tsx
  frontend/src/Components/ButtonMicrosoft.tsx
  frontend/src/Components/FirstStepOfSignUp.tsx
  frontend/src/Components/GoogleSignIn.tsx
  frontend/src/Components/PostSignUp.tsx
  frontend/src/Components/SVG/Apple.tsx
  frontend/src/Components/SVG/LeftArrow.tsx
  frontend/src/Components/SVG/PineCone.tsx
  frontend/src/Components/SVG/RemoveX.tsx
  frontend/src/Components/SVG/RightArrow.tsx
  frontend/src/Components/SecondLine.tsx
  frontend/src/Components/SecondStepOfSignUp.tsx
  frontend/src/Components/Sidebar.tsx
  frontend/src/Components/ThirdLine.tsx
  frontend/src/Components/ThirdStepOfSignUp.tsx
  frontend/src/Components/UserContext.tsx
  frontend/src/Components/test.tsx
  frontend/src/app/DashBoard/[id]/page.tsx
  frontend/src/app/InfoAboutStore/page.tsx
  frontend/src/app/Login/page.tsx
  frontend/src/app/SignUp/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#27 22 feature product
  backend/package-lock.json
  backend/package.json
  backend/src/controller/Product.ts
  backend/src/index.ts
  backend/src/model/Product.ts
  backend/src/router/Product.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Filter.tsx
  frontend/src/Components/Icon/Add.tsx
  frontend/src/Components/Icon/Approve.tsx
  frontend/src/Components/Icon/Arrow.tsx
  frontend/src/Components/Icon/Category.tsx
  frontend/src/Components/Icon/Date.tsx
  frontend/src/Components/Icon/Delete.tsx
  frontend/src/Components/Icon/Dollar.tsx
  frontend/src/Components/Icon/Edit.tsx
  frontend/src/Components/Icon/Image.tsx
  frontend/src/Components/Icon/Plus.tsx
  frontend/src/Components/Icon/Search.tsx
  frontend/src/Components/Icon/Vector.tsx
  frontend/src/Components/Turshilt.tsx
  frontend/src/Components/utils/Table.tsx
  frontend/src/Components/utils/Texts.tsx
  frontend/src/app/AddProduct/AddPro.tsx
  frontend/src/app/AddProduct/page.tsx
  frontend/src/app/Product/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#28 23 feature order
  backend/package-lock.json
  backend/package.json
  backend/src/controller/order.ts
  backend/src/index.ts
  backend/src/model/order.ts
  backend/src/router/order.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Icon/Arrow.tsx
  frontend/src/Components/Icon/Bell.tsx
  frontend/src/Components/Status.tsx
  frontend/src/app/AdminDashboard/Order/orderDetails/page.tsx
  frontend/src/app/AdminDashboard/Order/page.tsx
  frontend/src/app/page.tsx
Labels: Feature

#32 2 feature sign up
  backend/package.json
  backend/src/index.ts
  frontend/src/Components/DisAbledFirst.tsx
  frontend/src/Components/Filter.tsx
  frontend/src/Components/GoogleSignIn.tsx
  frontend/src/Components/Icon/Approve.tsx
  frontend/src/Components/ModalStore.tsx
  frontend/src/Components/SVG/CheckSvG.tsx
  frontend/src/Components/SVG/Circle.tsx
  frontend/src/Components/SVG/RightArrow.tsx
  frontend/src/Components/SVG/SearchSvG.tsx
  frontend/src/Components/Sidebar.tsx
  frontend/src/Components/SuccessModal.tsx
  frontend/src/Components/ThirdStepOfSignUp.tsx
  frontend/src/Components/Turshilt.tsx
  frontend/src/Components/utils/Texts.tsx
  frontend/src/app/AddProduct/AddPro.tsx
  frontend/src/app/AddProduct/page.tsx
  frontend/src/app/AdminDashboard/Order/orderDetails/page.tsx
  frontend/src/app/AdminDashboard/Order/page.tsx
  frontend/src/app/InfoAboutStore/page.tsx
  frontend/src/app/Product/page.tsx
  frontend/src/app/Settings/page.tsx
  frontend/src/app/SignUp/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#35 23 feature order
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/DateFilter.tsx
  frontend/src/Components/Icon/Calendar.tsx
  frontend/src/Components/OrderFilter.tsx
  frontend/src/Components/SVG/DownArrow.jsx
  frontend/src/Components/Status.tsx
  frontend/src/app/AdminDashboard/Order/page.tsx
  frontend/src/app/Order/page.tsx
  frontend/src/app/OrderDetails/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#37 8 feature filter by status
  backend/src/controller/order.ts
  backend/src/model/order.ts
  backend/src/model/user.ts
  frontend/src/Components/ButtonApple.tsx
  frontend/src/Components/ButtonGoogle.tsx
  frontend/src/Components/ButtonMicrosoft.tsx
  frontend/src/Components/DisAbledFirst.tsx
  frontend/src/Components/DisAbledSecond.tsx
  frontend/src/Components/DisabledThird.tsx
  frontend/src/Components/Filter.tsx
  frontend/src/Components/FirstStepOfSignUp.tsx
  frontend/src/Components/GoogleSignIn.tsx
  frontend/src/Components/ModalStore.tsx
  frontend/src/Components/OrderFilter.tsx
  frontend/src/Components/SecondStepOfSignUp.tsx
  frontend/src/Components/Sidebar.tsx
  frontend/src/Components/SuccessModal.tsx
  frontend/src/Components/SuccessProductModal.tsx
  frontend/src/Components/ThirdStepOfSignUp.tsx
  frontend/src/Components/TitlesOrder.tsx
  frontend/src/Components/UserContext.tsx
  frontend/src/Components/utils/StatesOfOrder.tsx
  frontend/src/Components/utils/Texts.tsx
  frontend/src/app/AddProduct/AddPro.tsx
  frontend/src/app/AddProduct/page.tsx
  frontend/src/app/EditProduct/EditPro.tsx
  frontend/src/app/EditProduct/page.tsx
  frontend/src/app/InfoAboutStore/page.tsx
  frontend/src/app/Order/page.tsx
  frontend/src/app/Product/page.tsx
  frontend/src/app/Settings/page.tsx
  frontend/src/app/SignUp/page.tsx
Labels: Feature

#38 22 feature product
  backend/package-lock.json
  backend/package.json
  backend/src/controller/Product.ts
  backend/src/controller/order.ts
  backend/src/controller/user.ts
  backend/src/index.ts
  backend/src/model/Product.ts
  backend/src/model/order.ts
  backend/src/model/user.ts
  backend/src/router/Product.ts
  backend/src/utils/s3.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Aws.tsx
  frontend/src/Components/Filter.tsx
  frontend/src/Components/GoogleSignIn.tsx
  frontend/src/Components/Icon/Arrow.tsx
  frontend/src/Components/Icon/Laptop.jpeg
  frontend/src/Components/ModalStore.tsx
  frontend/src/Components/PostSignUp.tsx
  frontend/src/Components/ThirdStepOfSignUp.tsx
  frontend/src/Components/UserContext.tsx
  frontend/src/Components/test.tsx
  frontend/src/app/AddProduct/AddPro.tsx
  frontend/src/app/AddProduct/page.tsx
  frontend/src/app/EditProduct/EditPro.tsx
  frontend/src/app/EditProduct/page.tsx
  frontend/src/app/InfoAboutStore/page.tsx
  frontend/src/app/Product/page.tsx
  frontend/src/app/Settings/page.tsx
  frontend/src/app/SignUp/page.tsx
  frontend/src/app/api/upload-image/route.ts
  frontend/src/app/page.tsx
Labels: Feature

#39 36 bug fix
  frontend/src/Components/Sidebar.tsx
  frontend/src/Components/Status.tsx
  frontend/src/app/Order/page.tsx
Labels: bug

#44 income
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/Income/page.tsx
Labels: Feature

#47 10 feature product filter by category
  backend/package-lock.json
  backend/package.json
  backend/src/controller/order.ts
  backend/src/model/order.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/DeliveryModal.tsx
  frontend/src/Components/DisAbledFirst.tsx
  frontend/src/Components/Filter.tsx
  frontend/src/Components/GoogleSignIn.tsx
  frontend/src/Components/Icon/Date.tsx
  frontend/src/Components/Icon/Delete.tsx
  frontend/src/Components/Icon/Edit.tsx
  frontend/src/Components/ModalStore.tsx
  frontend/src/Components/OrderFilter.tsx
  frontend/src/Components/ProductFIlterbyCategory.tsx
  frontend/src/Components/SecondStepOfSignUp.tsx
  frontend/src/Components/Sidebar.tsx
  frontend/src/Components/Status.tsx
  frontend/src/Components/ThirdStepOfSignUp.tsx
  frontend/src/Components/UserContext.tsx
  frontend/src/Components/utils/ByDates.tsx
  frontend/src/Components/utils/ByGenders.tsx
  frontend/src/Components/utils/UserInterFace.tsx
  frontend/src/app/Order/page.tsx
  frontend/src/app/OrderDetails/page.tsx
  frontend/src/app/Product/page.tsx
  frontend/src/app/Settings/page.tsx
  frontend/src/app/layout.tsx
Labels: Feature

#49 10 feature product filter by category
  frontend/src/Components/AuthProvider.tsx
  frontend/src/Components/Filter.tsx
  frontend/src/Components/GoogleSignIn.tsx
  frontend/src/Components/ThirdStepOfSignUp.tsx
  frontend/src/app/Product/page.tsx
  frontend/src/app/SignUp/page.tsx
  frontend/src/app/VerifyRoles/page.tsx
  frontend/tsconfig.json
Labels: enhancement

#53 fixed details
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Admin/Aws.tsx
  frontend/src/Components/Admin/Filter.tsx
  frontend/src/Components/Admin/Product.tsx
  frontend/src/Components/Admin/utils/Items.tsx
  frontend/src/app/Admin/AddProduct/AddPro.tsx
  frontend/src/app/Admin/AddProduct/page.tsx
  frontend/src/app/Admin/EditProduct/page.tsx
  frontend/src/app/Admin/Product/page.tsx
Labels: bug

#54 50 feature order filter
  .gitignore
  frontend/src/Components/Admin/Api_Admin/getAllUsers.ts
  frontend/src/Components/Admin/AuthProvider.tsx
  frontend/src/Components/Admin/DateFilter.tsx
  frontend/src/Components/Admin/FirstStepOfSignUp.tsx
  frontend/src/Components/Admin/GoogleSignIn.tsx
  frontend/src/Components/Admin/Sidebar.tsx
  frontend/src/Components/Admin/ThirdStepOfSignUp.tsx
  frontend/src/Components/Admin/utils/AdminCommodity.tsx
  frontend/src/Components/Admin/utils/AdminExperience.tsx
  frontend/src/Components/Admin/utils/Items.tsx
  frontend/src/Components/Admin/utils/OrderFilters.tsx
  frontend/src/app/Admin/DashBoard/[id]/page.tsx
  frontend/src/app/Admin/Order/page.tsx
  frontend/src/app/Admin/Product/page.tsx
  frontend/src/app/Admin/SignUp/page.tsx
  frontend/src/app/Admin/VerifyRoles/page.tsx
Labels: enhancement

#56 55 work on client side carousel
  frontend/src/Components/User/Api/FetchAllProducts.tsx
  frontend/src/Components/User/Carousel.tsx
  frontend/src/Components/User/Details.tsx
  frontend/src/Components/User/Isloading.tsx
  frontend/src/Components/User/Promotions/Blob.tsx
  frontend/src/Components/User/Promotions/ButtonStyle.css
  frontend/src/Components/User/Promotions/CircleOne.tsx
  frontend/src/Components/User/Promotions/ControlButton1.tsx
  frontend/src/Components/User/Promotions/ControlButton2.tsx
  frontend/src/Components/User/Promotions/ControlButton3.tsx
  frontend/src/Components/User/Promotions/Page1.tsx
  frontend/src/Components/User/Promotions/Page2.tsx
  frontend/src/Components/User/Promotions/Page3.tsx
  frontend/src/app/User/Details/[id]/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#60 made user footer
  frontend/src/Components/User/Footer.tsx
  frontend/src/Components/User/Icon/Facebook.tsx
  frontend/src/Components/User/Icon/Instagram.tsx
  frontend/src/Components/User/Icon/Twitter.tsx
  frontend/src/Components/User/Icon/index.ts
  frontend/src/Components/User/utils/Info.tsx
  frontend/src/Components/User/utils/Sort.tsx
  frontend/src/app/page.tsx
Labels: Feature

#61 navbar is made
  frontend/src/Components/User/Carousel.tsx
  frontend/src/Components/User/ContactMethod.tsx
  frontend/src/Components/User/HeadingBar.tsx
  frontend/src/Components/User/Icon/CartIcon.tsx
  frontend/src/Components/User/Icon/HeartIcon.tsx
  frontend/src/Components/User/Icon/MessageIcon.tsx
  frontend/src/Components/User/Icon/PhoneIcon.tsx
  frontend/src/Components/User/Icon/UserIcon.tsx
  frontend/src/Components/User/Icon/index.ts
  frontend/src/Components/User/NavbarClient.tsx
  frontend/src/Components/User/Promotions/ButtonStyle.css
  frontend/src/Components/User/Promotions/Page1.tsx
  frontend/src/Components/User/Promotions/Page2.tsx
  frontend/src/Components/User/Promotions/Page3.tsx
  frontend/src/app/layout.tsx
Labels: Feature

#63 48 feature orderdetails
  backend/src/controller/order.ts
  backend/src/router/order.ts
  frontend/src/Components/Admin/Icon/Arrow.tsx
  frontend/src/Components/Admin/Status.tsx
  frontend/src/app/Admin/Order/[orderId]/page.tsx
  frontend/src/app/Admin/Order/page.tsx
  frontend/src/app/Admin/OrderDetails/page.tsx
Labels: bug, Feature

#65 59 feature user product
  backend/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Admin/Aws.tsx
  frontend/src/Components/User/ElectronicProduct.tsx
  frontend/src/Components/User/Footer.tsx
  frontend/src/Components/User/Icon/Bucket.tsx
  frontend/src/Components/User/Icon/Like.tsx
  frontend/src/Components/User/Icon/Search.tsx
  frontend/src/Components/User/Icon/SearchPlus.tsx
  frontend/src/Components/User/Icon/index.ts
  frontend/src/Components/User/Products.tsx
  frontend/src/app/Admin/EditProduct/EditPro.tsx
  frontend/src/app/Admin/Product/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#66 62 feature login on client side
  frontend/src/Components/User/BreadCrumb.tsx
  frontend/src/Components/User/Carousel.tsx
  frontend/src/Components/User/Footer.tsx
  frontend/src/Components/User/FormsLogin.tsx
  frontend/src/Components/User/Functions/ValidInputs.tsx
  frontend/src/Components/User/HeadingBar.tsx
  frontend/src/Components/User/Icon/AtomIcon.tsx
  frontend/src/Components/User/Icon/UserIcon.tsx
  frontend/src/Components/User/Icon/index.ts
  frontend/src/Components/User/NavbarClient.tsx
  frontend/src/Components/User/Promotions/ButtonStyle.css
  frontend/src/app/User/LogIn/page.tsx
  frontend/src/app/layout.tsx
Labels: enhancement

#69 67 feature the content of home page on client side
  backend/src/model/Product.ts
  frontend/src/Components/User/AdditionalInfo.tsx
  frontend/src/Components/User/Api/GetOneProduct.tsx
  frontend/src/Components/User/Carousel.tsx
  frontend/src/Components/User/Cart.tsx
  frontend/src/Components/User/CartContext.tsx
  frontend/src/Components/User/CartHeading.tsx
  frontend/src/Components/User/Comment.tsx
  frontend/src/Components/User/Details.tsx
  frontend/src/Components/User/ExtraInfo.tsx
  frontend/src/Components/User/Functions/EventChange.tsx
  frontend/src/Components/User/Functions/ValidInputs.tsx
  frontend/src/Components/User/HeadingBar.tsx
  frontend/src/Components/User/Icon/GoldenStar.tsx
  frontend/src/Components/User/Icon/Minus.tsx
  frontend/src/Components/User/Icon/PlusIcon.tsx
  frontend/src/Components/User/Icon/Search.tsx
  frontend/src/Components/User/Icon/StarIcon.tsx
  frontend/src/Components/User/Icon/index.ts
  frontend/src/Components/User/Interface/ProductInterface.tsx
  frontend/src/Components/User/ProductDetail.tsx
  frontend/src/Components/User/Products.tsx
  frontend/src/Components/User/Promotions/ButtonStyle.css
  frontend/src/Components/User/Promotions/Page1.tsx
  frontend/src/Components/User/Promotions/Page2.tsx
  frontend/src/Components/User/Promotions/Page3.tsx
  frontend/src/Components/User/Ratings.tsx
  frontend/src/Components/User/Test.tsx
  frontend/src/Components/User/UserMiniNavbar.tsx
  frontend/src/Components/User/utils/AspectOfProduct.tsx
  frontend/src/Components/User/utils/QualitiesOfProduct.tsx
  frontend/src/Components/User/utils/TwoCategory.tsx
  frontend/src/app/Admin/Order/[orderId]/page.tsx
  frontend/src/app/User/BasketProduct/page.tsx
  frontend/src/app/User/Details/[id]/page.tsx
  frontend/src/app/User/GridDefault/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
Labels: Feature

#70 59 feature user product
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/User/ElectronicProduct.tsx
  frontend/src/Components/User/ProductDetail.tsx
  frontend/src/Components/User/Products.tsx
  frontend/src/Components/User/RelateProduct.tsx
  frontend/src/Components/User/UserMiniNavbar.tsx
  frontend/src/app/Admin/AddProduct/AddPro.tsx
  frontend/src/app/Admin/EditProduct/EditPro.tsx
Labels: Feature

#72 71 feature cart on client side
  frontend/src/Components/User/AsideCompletion.tsx
  frontend/src/Components/User/Carousel.tsx
  frontend/src/Components/User/Cart.tsx
  frontend/src/Components/User/CartContext.tsx
  frontend/src/Components/User/CartHeading.tsx
  frontend/src/Components/User/Details.tsx
  frontend/src/Components/User/Functions/IntoBasket.tsx
  frontend/src/Components/User/HeadingBar.tsx
  frontend/src/Components/User/Icon/X.tsx
  frontend/src/Components/User/Icon/index.ts
  frontend/src/Components/User/Interface/ContextType.tsx
  frontend/src/Components/User/Interface/UpdatedProduct.tsx
  frontend/src/Components/User/ProductCartContent.tsx
  frontend/src/Components/User/ProductDetail.tsx
  frontend/src/Components/User/SpecialProduct.tsx
  frontend/src/Components/User/UserMiniNavbar.tsx
  frontend/src/app/page.tsx
Labels: Feature

#73 45 dashboard
  backend/src/controller/dashboard.ts
  backend/src/index.ts
  backend/src/router/dashboard.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Admin/BestProduct.tsx
  frontend/src/Components/Admin/ChartTwo.tsx
  frontend/src/Components/Admin/Icon/BulletIcon.tsx
  frontend/src/Components/Admin/Icon/UserBlackIcon.tsx
  frontend/src/Components/Admin/Salechart.tsx
  frontend/src/app/Admin/DashBoard/[id]/page.tsx
  frontend/src/app/Admin/Dashboard/page.tsx
  frontend/src/app/Admin/Income/page.tsx
Labels: Feature
